<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE model [
  <!ATTLIST model class-name CDATA #REQUIRED>
  <!ATTLIST model type-safety-mode (AllPropsMustBeRegistered|AllPropsMustBeFirstSetWithSetIt|Loose) "AllPropsMustBeRegistered">
  <!ELEMENT model (props)>
  <!ELEMENT props (prop*)>
  <!ELEMENT prop (name, type)>
  <!ATTLIST prop use-reference-equality (true|false) "false" >
  <!ELEMENT name (#PCDATA)>
  <!ELEMENT type (#PCDATA)>
]>

<model class-name="SetAndGetModel" type-safety-mode="AllPropsMustBeFirstSetWithSetIt">
  <props>
    <prop use-reference-equality="true">
      <name>PropObject</name>
      <type>object</type>
    </prop>
    <prop>
      <name>PropString</name>
      <type>string</type>
    </prop>
    <prop>
      <name>PropBool</name>
      <type>bool</type>
    </prop>
    <prop>
      <name>PropInt</name>
      <type>int</type>
    </prop>
    <prop use-reference-equality="false">
      <name>
        Hello
      </name>
      <type>int</type>
    </prop>
  </props>
</model>
