=== drminor/propbag/PropBag/XMLModel/PropBagModel.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="model">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="namespaces" minOccurs="0" maxOccurs="1" />
        <xs:element ref="props" />
      </xs:sequence>
      <xs:attribute name="derive-from-pub-prop-bag" type="xs:boolean" default="false"/>
      <xs:attribute name="class-name" type="xs:string" use="required" />
      <xs:attribute name="output-namespace" type="xs:string" use="required" />
      <xs:attribute name="type-safety-mode" default="AllPropsMustBeRegistered" >
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="AllPropsMustBeRegistered" />
            <xs:enumeration value="OnlyTypedAccess" />
            <xs:enumeration value="Loose" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="defer-method-ref-resolution" type="xs:boolean" default="true"/>
      <xs:attribute name="require-explicit-initial-value" type="xs:boolean" default="true"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="namespaces">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="namespace" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="namespace" type="xs:string" />
  <xs:element name="props">
    <xs:complexType>
      <xs:sequence>
        <xs:element  ref="prop" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="prop">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="type" />
        <xs:element minOccurs="0" maxOccurs="1" ref="initial-value" />
        <xs:element minOccurs="0" maxOccurs="1" ref="comparer" />
        <xs:element minOccurs="0" maxOccurs="1" ref="do-when-changed" />
      </xs:sequence>
      <xs:attribute name="storage-strategy" type="xs:boolean" default="false"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string" />
  <xs:element name="type" type="xs:string" />
  <xs:element name="initial-value">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string" >
          <xs:attribute name="use-undefined" type="xs:boolean" default="false"/>
          <xs:attribute name="use-default" type="xs:boolean" default="false"/>
          <xs:attribute name="use-null" type="xs:boolean" default="false"/>
          <xs:attribute name="use-empty-string" type="xs:boolean" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="comparer">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string" >
          <xs:attribute name="use-reference-equality" type="xs:boolean" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="do-when-changed">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="do-after-notify" type="xs:boolean" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== drminor/propbag/PropBag.Test/TestAllPropsRegisteredModel_PropDefs.xml
<?xml version="1.0"?>
<model class-name="TestAllPropsRegistered" namespace="PropBagLib.Tests" type-safety-mode="AllPropsMustBeRegistered" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.swamphillproductions.com/PropBagModel ../PropBagModel/PropBagModel.xsd">
  <props>
    <prop>
      <name>PropObject</name>
      <type>object</type>
    </prop>
    <prop>
      <name>PropString</name>
      <type>string</type>
    </prop>
    <prop>
      <name>PropBool</name>
      <type>bool</type>
      <initial-value>false</initial-value>
    </prop>
    <prop>
      <name>PropInt</name>
      <type>int</type>
    </prop>
    <prop>
      <name>PropTimeSpan</name>
      <type>TimeSpan</type>
    </prop>
    <prop>
      <name>PropUri</name>
      <type>Uri</type>
    </prop>
    <prop>
      <name>PropLazyInt</name>
      <type>Lazy&lt;int&gt;</type>
    </prop>
  </props>
</model>

=== drminor/propbag/PropBag.Test/TestNullable_PropDefs.xml
<?xml version="1.0"?>
<model class-name="TestClass" namespace="PropBagLib.Tests" type-safety-mode="Loose" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.swamphillproductions.com/PropBagModel ../PropBagModel/PropBagModel.xsd">
  <props>
    <prop use-reference-equality="false">
      <name>PropNullableInt</name>
      <type>Nullable&lt;int&gt;</type>
    </prop>
    <prop use-reference-equality="false">
      <name>PropICollectionInt</name>
      <type>ICollection&lt;int&gt;</type>
    </prop>
  </props>
</model>

=== drminor/propbag/PropBag.Test/ExtStoreTests/ExtStoreModel_PropDefs.xml
<?xml version="1.0"?>
<model class-name="TestAllPropsRegistered" namespace="PropBagLib.Tests" type-safety-mode="AllPropsMustBeRegistered" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.swamphillproductions.com/PropBagModel ../../PropBagModel/PropBagModel.xsd">
  <namespaces>
    <namespace>System</namespace>
    <namespace>System.Collections.Generic</namespace>
    <namespace>PropBagLib.Tests</namespace>
  </namespaces>
  <props>
    <prop storage-type="external" >
      <name>PropObject</name>
      <type>object</type>
    </prop>
    <prop storage-type="external">
      <name>PropString</name>
      <type>string</type>
    </prop>
  </props>
</model>

=== drminor/propbag/PropBagT4/PropGen_PropDefs.xml
<?xml version="1.0"?>
<model class-name="TestAllPropsRegistered" namespace="PropBagLib.Tests" type-safety-mode="AllPropsMustBeRegistered" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://tempuri.org/PropBagModel ../PropBagModel/PropBagModel.xsd">
  <namespaces>
    <namespace>System</namespace>
    <namespace>System.Collections.Generic</namespace>
    <namespace>PropBagLib.Tests</namespace>
  </namespaces>
  <props>
    <prop>
      <name>PropObject</name>
      <type>object</type>
    </prop>
    <prop>
      <name>PropString</name>
      <type>string</type>
    </prop>
    <prop caller-provides-storage="false">
      <name>PropBool</name>
      <type>bool</type>
      <comparer use-reference-equality="true">xxx</comparer>
      <do-when-changed do-after-notify="true">yyy</do-when-changed>
    </prop>
    <prop caller-provides-storage="false">
      <name>PropInt</name>
      <type>int</type>
    </prop>
    <prop caller-provides-storage="false">
      <name>PropTimeSpan</name>
      <type>TimeSpan</type>
      <do-when-changed>DoWhenTimeSpanChanges</do-when-changed>
    </prop>
    <prop>
      <name>PropUri</name>
      <type>Uri</type>
      <comparer use-reference-equality="true"/>
      <do-when-changed do-after-notify="false">TestDelegate</do-when-changed>
    </prop>
    <prop>
      <name>PropLazyInt</name>
      <type>Lazy&lt;int&gt;</type>
      <initial-value>new Lazy&lt;int&gt;(() => 10)</initial-value>
      <comparer>MyTestComparer</comparer>
    </prop>
  </props>
</model>

=== drminor/propbag/PropBag.Test/PubPropBag/PubPropBagModel_PropDefs.xml
<?xml version="1.0"?>
<model
  derive-from-pub-prop-bag="true"
  class-name="PubPropBagModel"
  output-namespace="PropBagLib.Tests"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xsi:schemaLocation="https://www.swamphillproductions.com/PropBagModel ../../PropBag/XMLModel/PropBagModel.xsd">
  <namespaces>
    <namespace>System</namespace>
    <namespace>System.Collections.Generic</namespace>
  </namespaces>
  <props>
    <prop>
      <name>PropObject</name>
      <type>object</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropString</name>
      <type>string</type>
      <initial-value use-default="true"/>
      <do-when-changed>DoWhenStringChanged</do-when-changed>
    </prop>
    <prop>
      <name>PropStringCallDoAfter</name>
      <type>string</type>
      <initial-value use-undefined="true"/>
      <comparer>EqualityComparer&lt;string&gt;.Default.Equals</comparer>
      <do-when-changed do-after-notify="true">DoWhenStringChanged</do-when-changed>
    </prop>
    <prop>
      <name>PropStringUseRefComp</name>
      <type>string</type>
      <initial-value use-default="true"/>
      <comparer use-reference-equality="true"/>
      <do-when-changed do-after-notify="true">DoWhenStringChanged</do-when-changed>
    </prop>    
    <prop>
      <name>PropBool</name>
      <type>bool</type>
      <initial-value use-default="true"></initial-value>
    </prop>
    <prop>
      <name>PropInt</name>
      <type>int</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropTimeSpan</name>
      <type>TimeSpan</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropUri</name>
      <type>Uri</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropLazyInt</name>
      <type>Lazy&lt;int&gt;</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropNullableInt</name>
      <type>Nullable&lt;int&gt;</type>
      <initial-value>-1</initial-value>
      <do-when-changed>DoWhenNullIntChanged</do-when-changed>
    </prop>
    <prop>
      <name>PropICollectionInt</name>
      <type>ICollection&lt;int&gt;</type>
      <initial-value use-default="true"/>
      <do-when-changed>DoWhenICollectionIntChanged</do-when-changed>
    </prop>
  </props>
</model>

=== drminor/propbag/PropBag.Test/Performance/PerformanceModel_PropDefs.xml
<?xml version="1.0"?>
<model
  class-name="TestPerformance"
  output-namespace="PropBagLib.Tests"
  derive-from-class-mode="PropBag"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xsi:schemaLocation="https://www.swamphillproductions.com/PropBagModel ../../PropBag/XMLModel/PropBagModel.xsd">
  <namespaces>
    <namespace>System</namespace>
    <namespace>System.Collections.Generic</namespace>
    <namespace>PropBagLib.Tests</namespace>
  </namespaces>
  <props>
    <prop>
      <name>PropObject</name>
      <type>object</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropString</name>
      <type>string</type>
      <initial-value use-empty-string="true"/>
    </prop>
    <prop>
      <name>PropStringUseRefComp</name>
      <type>string</type>
      <initial-value use-default="true"/>
      <comparer use-reference-equality="true"/>
    </prop>    
    <prop>
      <name>PropBool</name>
      <type>bool</type>
      <initial-value>false</initial-value>
    </prop>
    <prop>
      <name>PropInt</name>
      <type>int</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropTimeSpan</name>
      <type>TimeSpan</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropUri</name>
      <type>Uri</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropLazyInt</name>
      <type>Lazy&lt;int&gt;</type>
      <initial-value use-default="true"/>
    </prop>
    <prop>
      <name>PropNullableInt</name>
      <type>Nullable&lt;int&gt;</type>
      <initial-value>-1</initial-value>
    </prop>
    <prop>
      <name>PropICollectionInt</name>
      <type>ICollection&lt;int&gt;</type>
      <initial-value use-null="true"></initial-value>
    </prop>
  </props>
</model>

=== drminor/propbag/PropBag.Test/TestNullablePropDefs.xml
<?xml version="1.0"?>
<model class-name="TestClass" type-safety-mode="Loose" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.swamphillproductions.com/PropBagModel ../PropBagModel/PropBagModel.xsd">
  <props>
    <prop use-reference-equality="false">
      <name>Prop1</name>
      <type>int</type>
    </prop>
    <prop use-reference-equality="false">
      <name>Prop2</name>
      <type>string</type>
    </prop>
    <prop use-reference-equality="false">
      <name>Prop3</name>
      <type>double</type>
    </prop>
  </props>
</model>

=== drminor/propbag/PropBag.Test/ExtStore/ExtStoreModel_PropDefs.xml
<?xml version="1.0"?>
<model
  class-name="TestExtStoreModel"
  output-namespace="PropBagLib.Tests"
  require-explicit-initial-value="false"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xsi:schemaLocation="https://www.swamphillproductions.com/PropBagModel ../../PropBagModel/PropBagModel.xsd">
  <namespaces>
    <namespace>System</namespace>
    <namespace>System.Collections.Generic</namespace>
    <namespace>PropBagLib.Tests</namespace>
  </namespaces>
  <props>
    <prop>
      <name>PropInt3</name>
      <type>int</type>
    </prop>
    <prop>
      <name>PropInt4</name>
      <type>int</type>
    </prop>
  </props>
</model>
