=== drminor/propbag/PropBag/XMLModel/PropBagModel.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="model">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="namespaces" minOccurs="0" maxOccurs="1" />
        <xs:element ref="props" />
      </xs:sequence>
      <xs:attribute name="derive-from-pub-prop-bag" type="xs:boolean" default="false"/>
      <xs:attribute name="class-name" type="xs:string" use="required" />
      <xs:attribute name="output-namespace" type="xs:string" use="required" />
      <xs:attribute name="type-safety-mode" default="AllPropsMustBeRegistered" >
        <xs:simpleType>
          <xs:restriction base="xs:NMTOKEN">
            <xs:enumeration value="AllPropsMustBeRegistered" />
            <xs:enumeration value="OnlyTypedAccess" />
            <xs:enumeration value="Loose" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:attribute name="defer-method-ref-resolution" type="xs:boolean" default="true"/>
      <xs:attribute name="require-explicit-initial-value" type="xs:boolean" default="true"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="namespaces">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="namespace" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="namespace" type="xs:string" />
  <xs:element name="props">
    <xs:complexType>
      <xs:sequence>
        <xs:element  ref="prop" minOccurs="0" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="prop">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="name" />
        <xs:element ref="type" />
        <xs:element minOccurs="0" maxOccurs="1" ref="initial-value" />
        <xs:element minOccurs="0" maxOccurs="1" ref="comparer" />
        <xs:element minOccurs="0" maxOccurs="1" ref="do-when-changed" />
      </xs:sequence>
      <xs:attribute name="storage-strategy" type="xs:boolean" default="false"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name" type="xs:string" />
  <xs:element name="type" type="xs:string" />
  <xs:element name="initial-value">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string" >
          <xs:attribute name="use-undefined" type="xs:boolean" default="false"/>
          <xs:attribute name="use-default" type="xs:boolean" default="false"/>
          <xs:attribute name="use-null" type="xs:boolean" default="false"/>
          <xs:attribute name="use-empty-string" type="xs:boolean" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="comparer">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string" >
          <xs:attribute name="use-reference-equality" type="xs:boolean" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
  <xs:element name="do-when-changed">
    <xs:complexType>
      <xs:simpleContent>
        <xs:extension base="xs:string">
          <xs:attribute name="do-after-notify" type="xs:boolean" default="false"/>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== drminor/propbag/PropBag.Test/AllPropsRegisteredModel_PropDefs.xml
<?xml version="1.0"?>
<model class-name="TestAllPropsRegistered" namespace="PropBagLib.Tests" type-safety-mode="AllPropsMustBeRegistered" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.swamphillproductions.com/PropBagModel ../PropBagModel/PropBagModel.xsd">
  <props>
    <prop>
      <name>PropObject</name>
      <type>object</type>
    </prop>
    <prop>
      <name>PropString</name>
      <type>string</type>
      <initial-value xsi:nil="true"/>
    </prop>
    <prop use-reference-equality="true">
      <name>PropStringUseRefComp</name>
      <type>string</type>
    </prop>    
    <prop>
      <name>PropBool</name>
      <type>bool</type>
      <initial-value>false</initial-value>
    </prop>
    <prop>
      <name>PropInt</name>
      <type>int</type>
    </prop>
    <prop>
      <name>PropTimeSpan</name>
      <type>TimeSpan</type>
    </prop>
    <prop>
      <name>PropUri</name>
      <type>Uri</type>
    </prop>
    <prop>
      <name>PropLazyInt</name>
      <type>Lazy&lt;int&gt;</type>
    </prop>
    <prop>
      <name>PropNullableInt</name>
      <type>Nullable&lt;int&gt;</type>
      <initial-value>-1</initial-value>
    </prop>
    <prop>
      <name>PropICollectionInt</name>
      <type>ICollection&lt;int&gt;</type>
    </prop>
  </props>
</model>
